### ISSUE TITLE
Do not attempt to create views when querying them

### ISSUE THREAD

**Issue by xrstf** [doctrine/couchdb-client#26]
I am creating a view query and the executing it. For this I don't provide a ``DesignDocument`` instance, because I don't need one (name of design doc and view are enough after all).

Unfortunately, whenever a query fails for _whatever_ reason, the query goes ahead and tries to **create** the view, which fails horribly because it has no DesignDocument to work with. As a nice side effect, the exception from not having a design document shadows the actual problem with my query.

It's completely wrong for a query (aka a reading access!) to suddenly create views in my database. Not only is it conceptionally wrong, it also won't work because my DB user has no write access (let alone being an admin that could fiddle with design documents). That's like Doctrine ORM trying a SELECT query and when it fails, it tries to create a table in my database.

For now I've worked around this by subclassing the Query and removing this weird error handling code.

**Comment by beberlei** [comment]
Fixed in ed6e036

**Comment by xrstf** [comment]
Thanks :)
