### ISSUE TITLE
HEAD request

### ISSUE THREAD

**Issue by Geolim4** [doctrine/couchdb-client#72]
Hello,

It seem that your HTTP client does not like very well HEAD request.
The whole script is blocked like it's waiting more data from the server.

Cheers,
Georges

**Comment by Geolim4** [comment]
Hello @beberlei can you have a look to this Pr please ? :)
Thanks !

**Comment by alexej-d** [comment]
I just ran into the same error where I was performing a replication for a target database which forces redirection to an SSL equivalent of its url. The request is stuck in a loop and always tries to request the http version of the target database…

**Comment by Geolim4** [comment]
@beberlei  Can  you have a look at my Pr please ?
Thanks !

**Comment by Geolim4** [comment]
Hello,

Ok, I have no choice but forking the library...
Sorry :/

Cheers,
Georges

**Comment by Geolim4** [comment]
I still want to highlight that this is very **sad** to release an unfinished library and not provide any support at it, or at least checking the submitted Pr's.
