### ISSUE TITLE
Abandoned

### ISSUE THREAD

**Issue by zorn-v** [doctrine/couchdb-client#75]
Famous "brand" doctrine, just abandon this repo. 
Relax guys and do forks for your tasks.
I think so.

Can anyone reach contributors to apply needed pull requests ?
https://github.com/doctrine/couchdb-client/pull/70
https://github.com/doctrine/couchdb-client/pull/74

**Comment by Geolim4** [comment]
At least it should be nice to have an official answer like "We does not support this lib anymore".
But getting snubbed is worse than everything :/

Cheers,
Georges

**Comment by damiankloip** [comment]
For now, we're maintaining our own fork of this, I have recreated some of the missing PR's to there too, see https://github.com/relaxedws/couchdb-client/pulls. I already merged  https://github.com/relaxedws/couchdb-client/pull/1 and https://github.com/relaxedws/couchdb-client/pull/2

**Comment by damiankloip** [comment]
@beberlei Do you have time to look at these PR's, or would it be a good idea to just maintain our fork of this? or collaborate on this repo?

**Comment by Geolim4** [comment]
Don't waste your time asking answer, it's not worst it... I send email, PM, tweets, etc. No one answer..

**Comment by robsonvn** [comment]
Hi guys

I've been adapting the project to work with CouchDB 2.0.

Check it out: https://github.com/robsonvn/couchdb-client

It includes:

- Mango Query #78 
- Passing in all tests
- Travis updated (CouchDB 2.0)
- SSL Support #70 

If any contributor appears we can create a new branch for this version.
