### ISSUE TITLE
Make timeout setting in AbstractHTTPClient configurable

### ISSUE THREAD

**Issue by meckhardt** [doctrine/couchdb-client#8]
There is a low timeout setting in the [AbstractHttpClient](/doctrine/couchdb-client/blob/18f1d301405139a60e602ac360745773bf6fd0be/lib/Doctrine/CouchDB/HTTP/AbstractHTTPClient.php#L27) that is not overwritten by any client.

This setting is used by the [StreamClient](/doctrine/couchdb-client/blob/18f1d301405139a60e602ac360745773bf6fd0be/lib/Doctrine/CouchDB/HTTP/StreamClient.php#L68) which can lead to exceptions and not successful responses.

We should make it configurable either by constructor argument or method.

Due to inheritance we could also add another options array for StreamClient but I think thats not a good style. We could also remove this setting completely

Regards,
Martin

**Comment by beberlei** [comment]
Implemented
