### ISSUE TITLE
Open to PR for posting to _find?

### ISSUE THREAD

**Issue by silverbackdan** [doctrine/couchdb-client#84]
Before I submit a PR writing the function into `CouchDBClient.php` (which would be pretty simple) - would you be open to having this to quickly send a `POST` request to the database `_find` endpoint to run Mango queries?

I'd imagine something like:
```php
    /**
     * Find a documents with a mango query
     *
     * @param array|string $query
     * @return HTTP\Response
     */
    public function findRequest($query)
    {
        if (!is_string($query) {
            $query = json_encode($query);
        }
        $findPath = '/' . $this->databaseName . '/_find';
        return $this->httpClient->request('POST', $findPath, $query);
    }
```

**Comment by robsonvn** [comment]
Bro, this library is abandoned. Have a look at my branch, it supports CouchDB 2.x including the _find endpoint. 
Cheers.

**Comment by robsonvn** [comment]
#86 already covers this, I hope you enjoy.
